---
title: "My IMDb Watchlist"
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# Set default chunk output
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  results = "asis"
)
```

```{r libraries}
library(tidyverse)
library(DT)
```


```{r data_load, include=FALSE}
my_ratings = read_csv("data/imdb_ratings.csv")
```

```{r nine_ten_movies, eval=FALSE}
nines_and_tens = my_ratings %>%
  filter(`Your Rating` %in% c(9, 10))

nines_and_tens %>%
  filter(`Title Type` == "movie") %>%
  select(`My Rating` = `Your Rating`, Title, `IMDb Rating`, `Runtime (mins)`, Year, Genres, `Release Date`, Directors) %>%
  arrange(desc(`My Rating`), desc(`IMDb Rating`)) %>%
  datatable(filter = "top", extensions = "Buttons",
            options = list(paging = FALSE, dom = "Bfrtip", buttons = c("copy", "csv", "excel"),
                           scrollY = "400px", scrollX = TRUE))
```

```{r full_list}
my_ratings %>%
  select(`My Rating` = `Your Rating`, Title, `Title Type`, `IMDb Rating`, `Runtime (mins)`, Year, Genres, `Release Date`, Directors) %>%
  arrange(desc(`My Rating`), desc(`IMDb Rating`)) %>%
  datatable(filter = "top", extensions = "Buttons",
            options = list(paging = FALSE, dom = "Bfrtip", buttons = c("copy", "csv", "excel"),
                           scrollY = "400px", scrollX = TRUE))
```



```{r some_graphs}
imdb_rating_plot = my_ratings %>%
  # select(`My Rating` = `Your Rating`, Title, `Title Type`, `IMDb Rating`, `Runtime (mins)`, Year, Genres, `Release Date`, Directors) %>%
  mutate(imdb_rating = round(`IMDb Rating`)) %>%
  group_by(imdb_rating, `Title Type`) %>%
  mutate(title_sample = ifelse(
    n_distinct(Title) < 10,
    paste(Title, collapse = "\n"),
    paste(sample(Title, 10, replace = FALSE), collapse = "\n"))) %>%
  group_by(title_sample, .add = TRUE) %>%
  count %>% ungroup() %>%
  ggplot(aes(x = imdb_rating, y = n, fill = `Title Type`, text = title_sample)) +
  geom_col() +
  scale_x_continuous(breaks = seq(1, 10, 1), limits = c(0.5, 10.5)) +
  theme_minimal() +
  labs(caption = "hi") +
  ylab("") + xlab("Imdb Rating") + ggtitle("Imdb's Rating (rounded)")

imdb_rating_plot %>% plotly::ggplotly() %>%
  plotly::layout(
    margin = list(
      b = 150 # Adjust the bottom margin to create space for the lower caption
    ),
    annotations = list(
      list(
        x = 0, y = -0.3, # Adjust x and y to position the lower caption
        xref = "paper", yref = "paper",
        text = "Hovering over each bar section will provide a sample list of ratings (10 max)",
        showarrow = FALSE,
        align = "left", # Align the text to the left
        font = list(size = 10) # Adjust the font size (change 10 to your desired size)
      )
    )
  )

my_rating_plot = my_ratings %>%
  # select(`My Rating` = `Your Rating`, Title, `Title Type`, `IMDb Rating`, `Runtime (mins)`, Year, Genres, `Release Date`, Directors) %>%
  # mutate(imdb_rating = round(`IMDb Rating`)) %>%
  group_by(`Your Rating`, `Title Type`) %>%
  mutate(title_sample = ifelse(
    n_distinct(Title) < 10,
    paste(Title, collapse = "\n"),
    paste(sample(Title, 10, replace = FALSE), collapse = "\n"))) %>%
  group_by(title_sample, .add = TRUE) %>%
  count %>% ungroup() %>%
  ggplot(aes(x = `Your Rating`, y = n, fill = `Title Type`, text = title_sample)) +
  geom_col() +
  scale_x_continuous(breaks = seq(1, 10, 1), limits = c(0.5, 10.5)) +
  theme_minimal() +
  ylab("") + xlab("Imdb Rating") + ggtitle("My Rating")

my_rating_plot %>% plotly::ggplotly() %>%
  plotly::layout(
    margin = list(
      b = 150 # Adjust the bottom margin to create space for the lower caption
    ),
    annotations = list(
      list(
        x = 0, y = -0.3, # Adjust x and y to position the lower caption
        xref = "paper", yref = "paper",
        text = "Hovering over each bar section will provide a sample list of ratings (10 max)",
        showarrow = FALSE,
        align = "left", # Align the text to the left
        font = list(size = 10) # Adjust the font size (change 10 to your desired size)
      )
    )
  )

my_ratings %>%
  select(my_rating = `Your Rating`, imdb_rating = `IMDb Rating`, title_type = `Title Type`) %>%
  ggplot(aes(y = my_rating, x = imdb_rating, colour = title_type)) +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 10, 1), limits = c(1, 10)) +
  scale_y_continuous(breaks = seq(0, 10, 1), limits = c(1, 10)) +
  coord_fixed(ratio = 1) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +
  ylab("My Rating") + xlab("IMDb Rating") + ggtitle("My Rating vs IMDB's Rating")

my_rating_vs_imdb = my_ratings %>%
  select(my_rating = `Your Rating`, imdb_rating = `IMDb Rating`) %>%
  mutate(diff = my_rating - imdb_rating,
         my_rating_greater = diff >= 0) %>%
  group_by(my_rating_greater) %>% count %>% ungroup() %>%
  mutate(perc = n / sum(n))

```

