---
title: "Cavan Donohoe's Resume"
author: Cavan Donohoe
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    self_contained: true
    css:
      - ./cv_stuff/cv_css.css
      - resume
knit: pagedown::chrome_print
editor_options: 
  chunk_output_type: console
lang: "en"
---
```{r ci-skip-gs4_cv, include=FALSE}
# if (Sys.getenv("CI") == "true") knitr::knit_exit()
```

```{r gs4-auth_cv, include=FALSE}
# googlesheets4::gs4_deauth()
```


```{r background code, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
# note for future cavan:
# you have to render this individually instead of just building the website
# that way the pdf version gets updated as well
# another note for future cavan... this may only work on mac

# coding in the resume

format_resume_date <- function(x) {
  vapply(x, function(value) {
    if (length(value) == 0 || all(is.na(value))) {
      ""
    } else if (inherits(value, "POSIXt") || inherits(value, "Date")) {
      format(as.Date(value), "%B %Y")
    } else {
      as.character(value)[1]
    }
  }, character(1))
}

# resume = read_excel(here::here("data", "resume.xlsx")
resume_url <- "https://docs.google.com/spreadsheets/d/13mLROsbvwiE-djiRMQuOKfQwppOlH5mOxB43EaGna8s"

# Error handling for Google Sheets API calls
resume <- tryCatch({
  googlesheets4::read_sheet(resume_url)
}, error = function(e) {
  warning("Failed to read resume from Google Sheets: ", e$message)
  # Fallback: try to read from local file if available
  if (file.exists(here::here("data", "resume.xlsx"))) {
    readxl::read_excel(here::here("data", "resume.xlsx"))
  } else {
    stop("Could not load resume data from Google Sheets or local file")
  }
})

file_info <- tryCatch({
  googledrive::drive_get(resume_url)
}, error = function(e) {
  warning("Failed to get file info from Google Drive: ", e$message)
  NULL
})

last_update <- if (!is.null(file_info) && length(file_info$drive_resource) > 0) {
  tryCatch({
    file_info$drive_resource[[1]]$modifiedTime |>
      lubridate::ymd_hms() |>
      lubridate::as_date()
  }, error = function(e) {
    warning("Failed to parse last update date: ", e$message)
    Sys.Date()
  })
} else {
  Sys.Date()
}

resume_v1.1 <- resume |>
  dplyr::mutate(dplyr::across(c(start, end), format_resume_date)) |>
  dplyr::mutate(dplyr::across(tidyselect::starts_with("description"), as.character)) |>
  dplyr::mutate(description_1 = dplyr::if_else(
    dplyr::if_all(tidyselect::starts_with("description"), ~ is.na(.x) | .x == ""),
    "[keep]",
    description_1
  )) |>
  dplyr::mutate(start.date = as.Date(paste(start, "1", sep = "-"), format = "%B %Y-%d")) |>
  dplyr::mutate(section_num = dplyr::row_number())

resume_v2 <- resume_v1.1 |>
  tidyr::pivot_longer(tidyselect::starts_with("description"),
                                         names_to = "description_num",
                                         values_to = "description",
                                         values_drop_na = TRUE)

resume_v3 <- resume_v2 |>
  dplyr::mutate(start = ifelse(is.na(start), "", start), end = ifelse(is.na(end), "", end)) |>
  dplyr::mutate(time_period = dplyr::case_when(start == "" ~ end,
                                 end == "" & section == "Awards" ~ start,
                                 TRUE ~ paste(start, end, sep = " - "))) |>
  dplyr::mutate(description_paste = ifelse(section != "About Me", paste("-", description),
    description)) |>
  dplyr::filter(in_resume)

pos_bullets <- resume_v3 |>
  dplyr::mutate(group_num = dplyr::cur_group_id()) |>
  dplyr::group_by(section, title, location, institution, time_period, section_num) |>
  dplyr::summarise(description_section = paste(description_paste, collapse = "\n")) |>
    dplyr::arrange(section_num)

pos_bullets_v1.1 <- pos_bullets |>
  dplyr::ungroup() |>
  dplyr::mutate(description_section = dplyr::case_when(
    section == "Skills" ~ gsub(
      x = description_section,
      pattern = "\\n",
      replacement = "\n\n"
    ),
    section %in% c("Awards", "Credentials") ~ gsub(
      x = description_section,
      pattern = "- ",
      replacement = ""
    ),
    TRUE ~ description_section
  ))

pos_bullets_v1.1[is.na(pos_bullets_v1.1)] <- "N/A"

# dealing with hyperlinks
pos_bullets_v1.2 <- pos_bullets_v1.1 |>
  dplyr::mutate(description_section = gsub(
    x = description_section,
    pattern = "Project Presentation",
    replacement = paste0(
      "[Project Presentation](",
      "http://www.math.ucla.edu/~actuary/caseCompetition/",
      "Case%20Comp%202018%20-%20Team%20UCI%20Presentation.pdf",
      ")"
    )
  )) |>
  dplyr::mutate(description_section = gsub(
    x = description_section,
    pattern = "Project Memorandum",
    replacement = paste0(
      "[Project Memorandum](",
      "http://www.math.ucla.edu/~actuary/caseCompetition/",
      "Case%20Comp%202018%20-%20Team%20UCI%20Executive%20Summary.pdf",
      ")"
    )
  ))

pos_bullets_v1.3 <- pos_bullets_v1.2 |>
  dplyr::mutate(description_section = dplyr::case_when(grepl(x = description_section,
    pattern = "\\[keep\\]") ~ "N/A",
                                         TRUE ~ description_section))

pos_bullets_final <- pos_bullets_v1.3

# adding word doc stuff too
rmarkdown::render("cv_doc.Rmd", output_format = "word_document", quiet = TRUE)
```

Aside
================================================================================



[Back to Home Page](https://cavandonohoe.github.io/)

[PDF version](https://github.com/cavandonohoe/cavandonohoe.github.io/raw/main/cv.pdf)

[Word version](https://github.com/cavandonohoe/cavandonohoe.github.io/raw/main/cv_doc.docx)




Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> cavandonohoe@gmail.com
- <i class="fa fa-github"></i> [github.com/cavandonohoe](https://github.com/cavandonohoe)
- <i class="fa fa-linkedin"></i> [linkedin.com/in/cavan-donohoe/](https://www.linkedin.com/in/cavan-donohoe/)
- <i class="fa fa-phone"></i> (805) 404-3321


Skills {#skills}
--------------------------------------------------------------------------------


```{r skills, echo=FALSE, results='asis'}
pos_bullets_final |>
  dplyr::filter(section == "Skills") |>
  dplyr::mutate(
    description_section = gsub(
      "website", "[website](https://cavandonohoe.github.io/)", description_section
    ),
    description_section = gsub(
      "resume", "[resume](https://cavandonohoe.github.io/cv.html)", description_section
    )
  ) |>
  glue::glue_data("{description_section}", "\n\n")
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r last_update`.



Main
================================================================================



Cavan Donohoe {#title}
--------------------------------------------------------------------------------

### Looking to improve your company's data workflow


```{r summary, echo=FALSE, results='asis'}
pos_bullets_final |>
  dplyr::filter(section == "About Me") |>
  glue::glue_data("{description_section}", "\n\n")
```



Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------


```{r professional experience, echo=FALSE, results='asis'}
pos_bullets_final |>
  dplyr::filter(section == "Experience") |>
  glue::glue_data("### {title}", "\n\n",
                                                                    "{institution}",
                                                                    "\n\n",
                                                                    "{location}",
                                                                    "\n\n",
                                                                    "{time_period}",
                                                                    "\n\n",
                                                                    "{description_section}",
                                                                    "\n\n",
                                                                    .na = "")
```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------


```{r education, echo=FALSE, results='asis'}
pos_bullets_final |>
  dplyr::filter(section == "Education") |>
  glue::glue_data("### {title}", "\n\n",
                                                                    "{institution}",
                                                                    "\n\n",
                                                                    "{location}",
                                                                    "\n\n",
                                                                    "{time_period}",
                                                                    "\n\n",
                                                                    "{description_section}",
                                                                    "\n\n",
                                                                    .na = "")
```




Awards {data-icon=medal}
--------------------------------------------------------------------------------


```{r awards, echo=FALSE, results='asis'}
pos_bullets_final |>
  dplyr::filter(section == "Awards") |>
  glue::glue_data("### {description_section}",
                                                                              "\n\n",
                                                                              "{institution}",
                                                                              "\n\n",
                                                                              "{location}",
                                                                              "\n\n",
                                                                              "{time_period}",
                                                                              "\n\n")
```

Credentials {data-icon=th-list}
--------------------------------------------------------------------------------


```{r credentials, echo=FALSE, results='asis'}

pos_bullets_final |>
  dplyr::filter(section == "Credentials") |>
  glue::glue_data("### {description_section}",
                                                                              "\n\n",
                                                                              "{institution}",
                                                                              "\n\n",
                                                                              "{location}",
                                                                              "\n\n",
                                                                              "{time_period}",
                                                                              "\n\n")
```
