---
title: "Jason, Owen, and Wyett's Schedule"
editor_options: 
  chunk_output_type: console
output:
  html_document:
    includes:
      in_header: header/header.html
      after_body: include_footer.html
---

```{r pipe, include=FALSE}
`%>%` <- magrittr::`%>%`
```

```{r setup, include=FALSE}
# Set default chunk output
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  results = "asis"
)
```

```{r}

# C schedule
wyetts_work_schedule <-
  tibble::tibble(days = seq.Date(as.Date("2025-01-12"), by = 1, length.out = 13203),
         bool = rep(c(1, 0, 1, 0, 1, 0, 0, 0, 0), 13203 / 9))


segments_and_weekends_c <- wyetts_work_schedule %>%
  dplyr::mutate(type =
           dplyr::case_when(
             # first day of 'weekend'
             (dplyr::lead(bool, n = 1) == dplyr::lead(bool, n = 2) &
                dplyr::lead(bool, n = 2) == dplyr::lead(bool, n = 3) |
                # second day of 'weekend'
                dplyr::lag(bool, n = 1) == dplyr::lead(bool, n = 1) &
                dplyr::lead(bool, n = 1) == dplyr::lead(bool, n = 2) |
                # third day of 'weekend'
                dplyr::lag(bool, n = 2) == dplyr::lag(bool, n = 1) &
                dplyr::lag(bool, n = 1) == dplyr::lead(bool, n = 1) |
                # fourth day of 'weekend'
                dplyr::lag(bool, n = 1) == dplyr::lag(bool, n = 2) &
                dplyr::lag(bool, n = 2) == dplyr::lag(bool, n = 3)) &
               bool == 0 ~ "weekend",
             TRUE ~ "segment"),
         work_status = dplyr::case_when(bool == 1 ~ "working",
                                 TRUE ~ "off"),
         day_of_week = weekdays(days))

years_till_retirement <- 65 - (lubridate::year(Sys.Date()) - 1994)

# fun code to check our overlap
# segments_and_weekends_c %>% 
#   dplyr::filter(day_of_week %in% c("Saturday", "Sunday") &
#            type == "weekend")

# B Schedule
jasons_work_schedule <-
  tibble::tibble(days = seq.Date(as.Date("2022-12-29"), by = 1, length.out = 13509),
         bool = rep(c(1, 0, 1, 0, 1, 0, 0, 0, 0), 13509 / 9))


segments_and_weekends_b <- jasons_work_schedule %>%
  dplyr::mutate(type =
           dplyr::case_when(
             # first day of 'weekend'
             (dplyr::lead(bool, n = 1) == dplyr::lead(bool, n = 2) &
                dplyr::lead(bool, n = 2) == dplyr::lead(bool, n = 3) |
                # second day of 'weekend'
                dplyr::lag(bool, n = 1) == dplyr::lead(bool, n = 1) &
                dplyr::lead(bool, n = 1) == dplyr::lead(bool, n = 2) |
                # third day of 'weekend'
                dplyr::lag(bool, n = 2) == dplyr::lag(bool, n = 1) &
                dplyr::lag(bool, n = 1) == dplyr::lead(bool, n = 1) |
                # fourth day of 'weekend'
                dplyr::lag(bool, n = 1) == dplyr::lag(bool, n = 2) &
                dplyr::lag(bool, n = 2) == dplyr::lag(bool, n = 3)) &
               bool == 0 ~ "weekend",
             TRUE ~ "segment"),
         work_status = dplyr::case_when(bool == 1 ~ "working",
                                 TRUE ~ "off"),
         day_of_week = weekdays(days))

# County schedule:
owens_work_schedule <-
  tibble::tibble(days = seq.Date(as.Date("2025-08-31"), by = 1, length.out = 12840),
         bool = rep(c(0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1), 12840 / 12))


segments_and_weekends_county <- owens_work_schedule %>%
  dplyr::mutate(type =
           dplyr::case_when(
             # first day of 'weekend'
             (dplyr::lead(bool, n = 1) == dplyr::lead(bool, n = 2) &
                dplyr::lead(bool, n = 2) == dplyr::lead(bool, n = 3) |
                # second day of 'weekend'
                dplyr::lag(bool, n = 1) == dplyr::lead(bool, n = 1) &
                dplyr::lead(bool, n = 1) == dplyr::lead(bool, n = 2) |
                # third day of 'weekend'
                dplyr::lag(bool, n = 2) == dplyr::lag(bool, n = 1) &
                dplyr::lag(bool, n = 1) == dplyr::lead(bool, n = 1) |
                # fourth day of 'weekend'
                dplyr::lag(bool, n = 1) == dplyr::lag(bool, n = 2) &
                dplyr::lag(bool, n = 2) == dplyr::lag(bool, n = 3)) &
               bool == 0 ~ "weekend",
             TRUE ~ "segment"),
         work_status = dplyr::case_when(bool == 1 ~ "working",
                                 TRUE ~ "off"),
         day_of_week = weekdays(days))
```

Jason, Owen, and Wyett's Work Schedule for the next `r years_till_retirement` years (Retire at 65 right?). Should be a fun journey for them! Keep battling those fires! 

This is based on the Kelly Schedule.

## Jason's:

```{r}
segments_and_weekends_b %>%
  dplyr::filter(days >= as.Date(Sys.Date())) %>%
  dplyr::select(date = days, day_of_week, work_status, type) %>%
  DT::datatable(filter = "top", extensions = "Buttons",
            options = list(paging = TRUE, dom = "Bfrtip", buttons = c("copy", "csv", "excel"),
                           pageLength = 500,
                           scrollY = "400px", scrollX = TRUE))
```

## Owen's:

```{r}
segments_and_weekends_county %>%
  dplyr::filter(days >= as.Date(Sys.Date())) %>%
  dplyr::select(date = days, day_of_week, work_status, type) %>%
  DT::datatable(filter = "top", extensions = "Buttons",
            options = list(paging = TRUE, dom = "Bfrtip", buttons = c("copy", "csv", "excel"),
                           pageLength = 500,
                           scrollY = "400px", scrollX = TRUE))
```

## Wyett's:

```{r}
segments_and_weekends_c %>%
  dplyr::filter(days >= as.Date(Sys.Date())) %>%
  dplyr::select(date = days, day_of_week, work_status, type) %>%
  DT::datatable(filter = "top", extensions = "Buttons",
            options = list(paging = TRUE, dom = "Bfrtip", buttons = c("copy", "csv", "excel"),
                           pageLength = 500,
                           scrollY = "400px", scrollX = TRUE))
```
