---
title: "Jason's Schedule"
editor_options: 
  chunk_output_type: console
output:
  html_document:
    includes:
      in_header: header/header.html
---

```{r setup, include=FALSE}
# Set default chunk output
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  results = "asis"
)
```

```{r libraries}
library(tidyverse)
library(DT)
```




```{r}
jasons_work_schedule =
  tibble(days = seq.Date(as.Date("2022-01-18"), by = 1, length.out = 13509),
         bool = rep(c(1, 0, 1, 0, 1, 0, 0, 0, 0), 13509 / 9))

# jasons_work_schedule %>%
#   filter(lead(bool, n = 1) == lead(bool, n = 2) & lead(bool, n = 2) == lead(bool, n = 3) & bool == 0)
# 
# jasons_work_schedule %>%
#   mutate(type = 
#            case_when(
#              lead(bool, n = 1) == lead(bool, n = 2) &
#                lead(bool, n = 2) == lead(bool, n = 3) & bool == 0 ~ "start of weekend"))

segments_and_weekends = jasons_work_schedule %>%
  mutate(type = 
           case_when(
             # first day of 'weekend'
             (lead(bool, n = 1) == lead(bool, n = 2) &
                lead(bool, n = 2) == lead(bool, n = 3) |
                # second day of 'weekend'
                lag(bool, n = 1) == lead(bool, n = 1) &
                lead(bool, n = 1) == lead(bool, n = 2) |
                # third day of 'weekend'
                lag(bool, n = 2) == lag(bool, n = 1) &
                lag(bool, n = 1) == lead(bool, n = 1) |
                # fourth day of 'weekend'
                lag(bool, n = 1) == lag(bool, n = 2) &
                lag(bool, n = 2) == lag(bool, n = 3)) &
               bool == 0 ~ "weekend",
             TRUE ~ "segment"),
         work_status = case_when(bool == 1 ~ "working",
                                 TRUE ~ "off"))

years_till_retirement = 65 - (lubridate::year(Sys.Date()) - 1994)
```

Jason's Work Schedule for the next `r years_till_retirement` years (Retire at 65 right?)

```{r}
segments_and_weekends %>%
  filter(days >= as.Date(Sys.Date())) %>% 
  select(date = days, work_status, type) %>% 
  datatable(filter = "top", extensions = "Buttons",
            options = list(paging = FALSE, dom = "Bfrtip", buttons = c("copy", "csv", "excel"),
                           scrollY = "400px", scrollX = TRUE))
```


