---
title: "Blog"
output:
  html_document:
    includes:
      in_header: header/header.html
    number_sections: no
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: true
      smooth_scroll: true
editor_options: 
  chunk_output_type: console
---

Please note, I have pictures on my Instagram so I won't have any pictures on this blog. Give me a follow 😊

<a href="https://www.instagram.com/cavandonohoe"><i class="fa fa-instagram" style="font-size:36px"></i></a>

### Week of May 16th, 2022

Travelling to a new place for the first time can be both exhilarating and nerve-wracking. Especially when it's outside of your comfort zone. I recently had the opportunity to travel to Madrid, Spain for a week, which marked my first international trip outside of North America. And let me tell you, it was an experience I will never forget.

Madrid is a vibrant city filled with history, art, culture, and amazing food. The city is a mix of old and new, with beautiful architecture that has stood the test of time. One of the first things that struck me about Madrid was the warmth of the people. From the airport to the streets, everyone was friendly and welcoming, making me feel right at home.

As I explored the city, I found myself constantly in awe of the stunning buildings, monuments, and parks. The Royal Palace of Madrid, with its intricate details and grandeur, was one of my favorite sights. Walking through the Puerta del Sol, one of the busiest squares in Madrid, I felt like I was part of the hustle and bustle of city life.

But what I enjoyed most about Madrid was its food culture. From tapas to paella, Spanish cuisine is world-renowned for its bold flavors and deliciousness. I visited many local restaurants and cafes, trying everything from traditional Spanish dishes to fusion cuisine. My personal favorite was a small tapas bar in the Malasaña neighborhood that served the most amazing patatas bravas I have ever tasted. And some dank sangria!

One of the biggest challenges I faced during my trip was the language barrier. Although many people in Madrid speak English, it was still difficult at times to communicate effectively. However, I quickly learned that a smile and a willingness to try to speak Spanish went a long way in breaking down barriers and building connections with the locals. Plus, Google Translate was super effective with ordering food and what not. Also, in a lot of places in Europe, they won't come around with the bill, so you'll actually have to get the courage to ask them. 

In conclusion, my first international trip to Madrid was a life-changing experience. It opened my eyes to a new culture, language, and way of life. It taught me to be more adventurous and open-minded, and to embrace new experiences with enthusiasm. I can't wait to plan my next international adventure and see what other exciting opportunities await.

Also, I just thought of a little bit more to add to this...

Certainly, working remotely while traveling can be a unique experience, and Madrid was no exception. Despite the time difference, I was able to maintain my work schedule in the Pacific Time Zone while enjoying everything the city had to offer. So my schedule ended up being a fun period of exploring whichever city I was in from 10am - 6pm, work from 6pm - 2am, then sleep from 2am - 10am. Then repeat :D

One of the perks of working remotely while traveling is the flexibility it provides. I could explore the city during the day, try different foods, and visit museums and landmarks, all while still being able to attend virtual meetings and complete my work tasks.

Working remotely also allowed me to immerse myself more fully in the local culture. I visited local cafes and co-working spaces, where I had the opportunity to meet locals and other travelers who were also working remotely. It was interesting to learn about their experiences and how they balanced work and travel.

Overall, working remotely in Madrid was a great experience. It gave me the freedom to travel and explore a new city while also staying on top of my work responsibilities. I would highly recommend it to anyone who has the opportunity to do so.

To get real for a sec: This was a good start to the trip. I started walking a bunch and really enjoyed seeing everyone else there. It was pretty warm there and there wasn't great water in the Airbnb butttt it was really awesome going to the nearby square (plaza) to get more water. And people were there till I was done working at 2am. I should have struck up a conversation with some random people over there. Oh well, missed opportunity.

### Week of May 23rd, 2022

Biking the Amalfi Coast is one of the most iconic experiences in Italy. The stunning coastal views, charming towns, and delicious food make it a must-see destination for any traveler. But what happens when you rent an electric bike and are too proud to use the electric part? That's exactly what happened to me during my trip to Naples, Italy.

After spending a week in Madrid, I was ready for my next adventure. I decided to visit Naples and rent an electric bike to explore the Amalfi Coast. However, when I picked up the bike, I forgot to turn on the electric assist. As a result, I was left with a heavy bike that was difficult to pedal, especially on the steep hills of the Amalfi Coast.

Despite the challenging start, I decided to embrace the experience and set off on my adventure. I took a train to Salerno, a town at the southern end of the Amalfi Coast, and started my bike ride along the winding roads that hug the coastline.

The views were breathtaking. The turquoise waters of the Tyrrhenian Sea sparkled in the sunlight, and the colorful houses perched on the hillsides added to the charm of the towns. However, as the day went on, I began to feel the strain of pedaling a heavy bike uphill.

At times, I had to slow down and catch my breath but never ever push my bike. It was actually impossible to walk with a bike on the windy streets of the Amalfi Coast just because the streets were so narrow. It was exhausting though. But with each turn, the stunning views made it all worth it. I passed through charming towns like Vietri sul Mare, Amalfi, and Positano, each with its unique character and beauty.

As the sun began to set, I reached the end of my bike ride and arrived back in Sorrento. However, the adventure wasn't quite over. When I tried to take the bike on the train back to Naples, I was told that I couldn't because of the size of the bike. I had to pedal the entire way back to Naples, which was challenging, but also a fitting end to the day's adventure.

In conclusion, biking the Amalfi Coast on a heavy bike was a unique experience. While it was challenging at times, it was also incredibly rewarding. The stunning views, charming towns, and sense of accomplishment made it a trip I will never forget. It reminded me that sometimes, the most memorable experiences come from stepping out of your comfort zone and embracing the journey, even if it doesn't go as planned.

This trip also featured Janella and Becky who made the trip so much better. I realized how nice it was to have a balance of seeing friends and also doing my own thing. It does get lonely if it's just me doing my own thing days on end. But then again, you'd think I'd get lonely on that massive 75 mile bike ride along the Amalfi Coast. But for some reason, that felt great. This form of long term traveling seems to get me to learn more and more about myself.

### May 30th - June 19th 2022

Rome is one of the most vibrant and historic cities in the world, and I had the opportunity to explore it for three weeks. During my trip, I stayed at my friend Mauro's place, watched the 2022 FIVB World Tour Finals tournament, and had an amazing time. I also got to hangout with Shannon Costa and got to meet some of my favorite volleyball players in the world! Mauro was only there for one week too! It's very funny because he was only there for one week, while I was there for 3...

One of the best things about staying with a local is that you get a unique perspective on the city. Mauro was a great host, showing me the hidden gems of Rome that are often overlooked by tourists. We had some truly authentic Italian food and he showed me things my tongue only dreamed about. Like in a non sexual way. It was a great way to immerse myself in the local culture and get a true taste of Rome.

One of the highlights of my trip was attending the 2022 FIVB World Tour Finals tournament. The tournament featured some of the best volleyball players in the world, and the matches were intense and exciting. I got to see top teams from around the world compete, and the atmosphere in the stadium was electric. I got to meet a bunch of Norwegians who offered me to let them stay with them up in Oslo! So I'll be going in the summer of 2023 to see if they're still down for that.

Apart from the volleyball tournament, there was so much to see and do in Rome. I visited famous landmarks like the Colosseum, the Vatican, and the Pantheon, and each one was more impressive than the last. The history and art in Rome are breathtaking, and it's incredible to think about the stories that each monument and building holds.

I also enjoyed wandering around the city, getting lost in the narrow streets and stumbling upon hidden treasures. Rome is a city that rewards exploration, and I loved discovering new places and experiences.

Of course, no trip to Rome is complete without trying the food. From pizza and pasta to gelato and espresso, every meal was a culinary adventure. Mauro took me to his favorite local spots, where we indulged in delicious dishes and soaked up the atmosphere. And let me tell you the carbonara was so so so good!! I still dream of that pasta dish to this day.

Overall, my three weeks in Rome were a fantastic experience. Staying with a local gave me a unique perspective on the city, and the FIVB tournament added an extra layer of excitement. Rome is a city that has so much to offer, from its history and culture to its food and nightlife. It's a place that I will always hold dear to my heart, and I can't wait to go back and explore more.

One last thing btw... There is a spot in Rome called Yellow Door Hostel Bar that was so incredible! I went only twice, but I had the best time ever! If I wasn't staying on the other side of town, I would have gone more often. I met so many friendly faces there! And every time I went, there were hardly any outdoor spots to sit, so you would have to share a table with other people there. Which ends up building some long term relationships with these people. And everyone spoke English too which was huge! 

### Week of June 20th

Dubrovnik is a picturesque city located on the Adriatic coast of Croatia. It's known for its stunning medieval architecture, charming streets, and crystal-clear waters. I had the opportunity to explore this beautiful city for a week, and it was an unforgettable experience.

One of the things that stood out to me about Dubrovnik was its history. The city has been around for centuries and has gone through many transformations over the years. I had the chance to walk along the ancient city walls and admire the stunning views of the red-tiled roofs and the sparkling sea. It was fascinating to see how the city has evolved over the centuries, and I felt like I was stepping back in time.

Another highlight of my trip was exploring the Old Town. The cobblestone streets, stone buildings, and charming squares were like something out of a fairy tale. I spent hours wandering through the narrow alleys and admiring the architecture. The city is so well preserved that it's easy to imagine what life was like in the past. I felt like Hulk in Endgame... SO MANY STAIRS. I got a nice butt workout from this experience. It was really hot there too, so I was a sweaty mess.

Of course, no trip to Dubrovnik is complete without spending time by the sea. The beaches and coves in Dubrovnik are some of the most beautiful I've ever seen. I spent several afternoons swimming in the clear water and sunbathing on the rocky beaches. It was a wonderful way to relax and take in the natural beauty of the city.

Overall, my week in Dubrovnik was an amazing adventure. The city is full of history, culture, and natural beauty. I loved exploring the Old Town, swimming in the sea, and trying the delicious food. It's a place that I would highly recommend to anyone looking for a unique and unforgettable travel experience.

I mean and living in King's Landing for a week was dope too. I was just listing to the theme music for hours on end. I recommend walking along the wall in the Old City. Best walk around the city I've had! Plus you're up so high without any railings, so that's a thrill too. 

I stayed in an Airbnb in the Port of Dubrovnik, so I got to see a beautiful view from my pad every day while I worked over there. 

### Weekend of June 25th

Zagreb is the capital of Croatia and a vibrant city with a rich history and culture. I had the opportunity to explore this charming city for a weekend and it was a fantastic experience. I also took a quick visit to Plitvice Lakes National Park, which was a highlight of my trip.

Zagreb has a fascinating history that's reflected in its architecture and culture. The city is a blend of medieval and modern, with colorful buildings, narrow streets, and spacious parks. I spent most of my time wandering around the streets and exploring the local markets. The city has a lively atmosphere with street musicians, cafes, and bars. It was a great place to soak up the local culture.

One of the highlights of my trip was visiting the Plitvice Lakes National Park. The park is a UNESCO World Heritage Site and one of the most beautiful natural wonders of Croatia. The park features a series of cascading waterfalls, crystal-clear lakes, and lush green forests. I spent several hours hiking around the park and admiring the stunning scenery. It was a peaceful and magical experience that left me in awe. I took a picture of a waterfall while I was on a waterfall!!

Back in Zagreb, I enjoyed trying the local cuisine. Croatian food is delicious and diverse, with influences from Italy, Austria, and the Balkans. I tried traditional dishes like grilled meats, seafood, and pasta, and I also enjoyed the local wines and spirits. The local markets are also a great place to sample fresh fruits, vegetables, and cheeses.

Overall, my weekend trip to Zagreb with a quick visit to Plitvice was a wonderful adventure. The city is full of history, culture, and great food. Plitvice Lakes National Park was a stunning natural wonder that left me breathless. It's a place that I would highly recommend to anyone looking for a unique and unforgettable travel experience.

Also, I got to hostel with Janella! And that was a blast! What a fun time with a fun person! And I stayed in my very first hostel and got to experience that type of craziness and cool people! 

Oh btw, on my way to Plitvice I missed my bus stop so I got off and started walking back towards Plitvice and ended up getting a ride from a nice stranger. And I didn't get murdered! Hurray! 

### Week of June 27th

Split is a charming coastal city located in southern Croatia. It's known for its beautiful beaches, stunning architecture, and vibrant nightlife (of which I didn't partake since I am not huge into loud clubs). I had the opportunity to explore this wonderful city for a week, and it was an amazing experience.

One of the highlights of my trip to Split was exploring the historic Old Town. The city is over 1,700 years old, and it's packed with incredible sights and sounds. I spent hours wandering through the narrow streets, admiring the beautiful architecture, and exploring the local markets. One of the must-see sights in Split is the Diocletian's Palace, which was built in the 4th century and is now a UNESCO World Heritage Site.

Another highlight of my trip was the local cuisine. Croatian food is delicious and diverse, and Split is a great place to sample it. I tried traditional dishes like grilled fish and meat, fresh seafood, and pasta. I also enjoyed the local wines and spirits, which added to the experience.

Overall, my week in Split was a fantastic adventure. The city is full of history, culture, and natural beauty. I loved exploring the Old Town, trying the delicious food, and spending time by the sea. The vibrant nightlife was also a highlight of my trip. It's a place that I would highly recommend to anyone looking for a fun and unforgettable travel experience.

Another round of hitting the hostel in this town too! I had a fun little time over there exploring the city on the last few days with Janella again! 

### Weekend of July 1st

So this was a crazy weekend. It started on a delayed flight from Split to Milan. Then I took a train over to Como to see how beautiful the lake was over there and also to go to that mansion where Attack of the Clones was filmed. Butttt I didn't have time because I needed to make a bus from Milan to Nice. And I ended up missing my bus anyways because of train delays! I was so close to making it too! Oh well. I payed for an overpriced bus ticket to get from Milan to Nice with a stop in Lyon. But the stop in Lyon was excellent! I had an amazing macaron and an amazing croissant! I dream about that! Omg!

Anyways, I ended up making it to Nice with very little sleep on that bus ride, but hey... I made it.

Nice is a beautiful coastal city located in the south of France. It's known for its stunning beaches, colorful buildings, and vibrant culture. I had the opportunity to explore this charming city for a weekend with Daphney, and it was an incredible experience. I also had the chance to meet two fun guys from Miami who offered to take me on a day trip to Monaco since. Part of the fun of these trips is getting to meet new people and it is so easy to meet new people when I am with a fun person on that trip. So thank you, Daphney for making it easy to make friends with these people.

The first thing that struck me about Nice was the beautiful architecture. The city is full of colorful buildings, narrow streets, and quaint cafes. I spent most of my time exploring the local markets, trying the delicious food, and soaking up the local culture. Nice has a lively atmosphere with street performers, musicians, and artists. It was a great place to relax and take in the local scenery.

One of the highlights of my trip was meeting the two guys at my Airbnb who invited me to join them on a day trip to Monaco. They had a cabana at this club overlooking the sea on one side and the speedway track on the other and offered to take me along for free. It was an incredible experience. We spent the day swimming in the pool and pretending to be rich. We met other people who were probably doing the same exact thing. Monaco is a stunning city with luxurious buildings and beautiful scenery. We visited the famous Monte Carlo casino and enjoyed the local shops and restaurants. It was a great day and one that I will never forget.

Back in Nice, I also spent the evening hiking up to the castle at the top of the hill. I find all of France just has an atmosphere of romanticism. I loved seeing the lights at night and all of the beauty of the city from above.

Sidenote: I'm an idiot for not having ratatouille in France...

Overall, my weekend trip to Nice with a day trip to Monaco was a fantastic adventure. The city is full of history, culture, and natural beauty. The local cuisine was delicious, and the beaches were stunning. The chance encounter with the two fun guys from Miami who took me to Monaco was a highlight of my trip. It's a place that I would highly recommend to anyone looking for a unique and unforgettable travel experience.

Also, the beaches are pebbly beaches, so I recommend sandals or shoes. So watch out for that.

### Week of July 4th

Happy Independence Day! First one I have experienced being away from the US.

Marseille is a beautiful city located in the south of France. It's known for its stunning coastline, historic landmarks, and vibrant culture. I had the opportunity to spend a week exploring this charming city and even took a day trip to Paris.

Marseille has a rich history and a unique culture. The city is full of historic landmarks, including the Basilique Notre-Dame de la Garde, a beautiful basilica perched on a hill overlooking the city. I also visited the Old Port, a bustling area filled with restaurants, cafes, and shops. The locals are friendly and welcoming, and I enjoyed chatting with them and learning more about their way of life.

One of the highlights of my trip was a day trip to Paris. It's only a three-hour train ride from Marseille, so it was easy to take a day trip. I visited some of the most famous landmarks in Paris, including the Eiffel Tower, the Louvre Museum, and Notre-Dame Cathedral. It was a busy day, but I managed to see a lot of the city in a short amount of time. And Phoebe Hung let me stay at her place and also play tour guide to the city she was living in for the summer! Crazy enough was I never actually had a real conversation with Phoebe until Paris and then we ended up talking for 8 hours! That was crazy!

Back in Marseille, I spent time exploring the local beaches. But really just one beach in particular. I am too lazy right now to look it up, but I played so much volleyball with the locals over there! Just by saying I played volleyball in California, they automatically took me in and saw me as an expert (even though I have been playing for `r lubridate::year(Sys.Date()) - 2007` years, I still don't consider myself an expert). But hey, I played with some French people and that was a fun time!

The local cuisine was another highlight of my trip. Marseille is famous for its seafood, and I enjoyed some of the freshest and most delicious seafood I've ever had. I also tried traditional dishes like bouillabaisse, a fish stew that originated in the area, and enjoyed local wines and spirits.

Overall, my week in Marseille with a day trip to Paris was a fantastic adventure. The city is full of history, culture, and natural beauty. The locals are friendly and welcoming, and the food is delicious. The day trip to Paris was a great way to see some of the most famous landmarks in the world, and I'm glad I took the time to explore this beautiful city. It's a trip that I will never forget and one that I would highly recommend to anyone looking for a unique and unforgettable travel experience.

I also hungout with some people at the local hostel bar! Which I should remember to do that sooner in my travels so I can make friends earlier. But whatever, still a fun time! 

### Week of July 11th

Barcelona is a vibrant city located on the northeastern coast of Spain. It's known for its stunning architecture, delicious food, and lively culture. I had the opportunity to spend a week exploring this incredible city, and it was an experience I will never forget.

One of the highlights of my trip was visiting the iconic Sagrada Familia, a massive basilica that has been under construction since 1882. The intricate details and stunning design of the basilica were truly breathtaking, and it was amazing to see the progress that has been made on this incredible structure.

I walked along La Rambla, a bustling street lined with shops, restaurants, and street performers, and explored the Gothic Quarter, a historic area filled with narrow streets, beautiful buildings, and fascinating history.

The food in Barcelona was another highlight of my trip. I indulged in traditional dishes like paella and patatas bravas. I also enjoyed delicious tapas and local wines, and explored the city's vibrant food scene. Of course I had sangria... I mean come on.

Aside from the city's attractions, I also spent time relaxing on the beach and taking in the beautiful Mediterranean Sea. Barcelona has some of the best beaches in Europe, and it was a great way to unwind and soak up the sun.

And of course there was so much volleyball every single day! That place was awesome!!! I've never been welcomed by so many people before! Seriously the nicest people to ever play the sport and just welcome in strangers like no problem. That would never happen in the US to strangers. But hey, Europeans are nicer I suppose.

Overall, my week in Barcelona was an incredible experience. The city is full of history, culture, and natural beauty. The architecture is stunning, the food is delicious, and the people are friendly and welcoming. It's a trip that I will never forget and one that I would highly recommend to anyone looking for a unique and unforgettable travel experience.

And hey that was the end of my 2022 Euro Trip. Come back shortly for my 2023 Euro Trip...

### My First Autumn (October 30th - November 13th)

Autumn is a beautiful season in the northeastern United States, with the changing leaves creating a stunning display of colors. I had the opportunity to spend two weeks in November exploring the area around New Brunswick, New York City, and Philadelphia, and it was an incredible trip.

I started my trip with New York City, which was bustling with energy and excitement. And it was warm! It was like 72 degrees as the high when I was there. I thought I needed to bring more sweats and sweatshirts on my trip, but surprisingly, I didn't need them! The city was also filled with beautiful autumn leaves, especially in Central Park. I spent a day exploring the park, taking in the colorful foliage and enjoying the crisp fall air. I spent a lot of time playing volleyball and walking as much as I could! When I was able to wander and spend more time around the city, I skipped the subway and chose to walk the 10 miles. It was beautiful as a California native! I got to see Alex Morris for the 4th time this year! Truly the nicest person I have ever met and it was lovely seeing her! I hope she and Max get engaged! 

Also, I got to stay in the Lower East Side with a friend and she had an incredible high rise apartment with an awesome view! Such a cool experience being there!

Next, I headed to New Brunswick, NJ, where I stayed with friends (Mina and Ted - who are moving to California in March 2023!) who showed me around the area. They live next to this beautiful tree filled with reds, oranges, and yellows in their leaves and my eyes were truly seeing some true beauty for the first time. 

From there, I took a short train ride to Philadelphia, which was also full of autumn beauty. I explored the historic Old City neighborhood, where I saw the Liberty Bell and Independence Hall, and visited the beautiful Fairmount Park, which was full of colorful trees and peaceful trails. I got to see my cousin, Blake, and met his son, Wesley, for the first time! Such a fun time over there!

Throughout my trip, I always try some tasty foods and I will always go to Joe's Pizza whenever I'm in NYC. I also went to a club in NYC where they played 'Empire State of Mind' which everyone lost their shit over. Also had Philly cheesesteak for the first time. In Philadelphia! Crazy stuff, I know.

Overall, my two-week trip to New Brunswick, NJ, NYC, and Philly to see autumn leaves was a beautiful and memorable experience. I highly recommend this trip to anyone who wants to explore the natural beauty and vibrant culture of the northeastern United States in the fall.

