<!DOCTYPE html>

<html lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Cavan Donohoe" />


<title>Lesson 5: Statistics with R</title>

<script src="site_libs/header-attrs-2.31/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-P51TN2DWZM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-P51TN2DWZM', {
    'anonymize_ip': true
  });
</script>
<!-- Favicons and app icons -->
<link rel="apple-touch-icon" sizes="180x180" href="/header/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/header/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/header/favicon-16x16.png">
<link rel="manifest" href="/header/site.webmanifest">
<link rel="mask-icon" href="/header/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<!-- Dark mode + site-wide styling -->
<style>
:root {
  --bg-color: #fff;
  --text-color: #333;
  --card-bg: #f8f9fa;
  --card-border: #dee2e6;
  --card-shadow: rgba(0,0,0,0.08);
  --link-color: #337ab7;
  --code-bg: #f5f5f5;
  --table-stripe: #f9f9f9;
  --accordion-bg: #337ab7;
  --accordion-hover: #286090;
  --muted-text: #777;
  --footer-text: #ccc;
  --well-bg: #f5f5f5;
}

[data-theme="dark"] {
  --bg-color: #1a1a2e;
  --text-color: #e0e0e0;
  --card-bg: #16213e;
  --card-border: #0f3460;
  --card-shadow: rgba(0,0,0,0.3);
  --link-color: #64b5f6;
  --code-bg: #16213e;
  --table-stripe: #16213e;
  --accordion-bg: #0f3460;
  --accordion-hover: #1a4a8a;
  --muted-text: #aaa;
  --footer-text: #999;
  --well-bg: #16213e;
}

body {
  background-color: var(--bg-color) !important;
  color: var(--text-color) !important;
  transition: background-color 0.3s ease, color 0.3s ease;
}

[data-theme="dark"] .container-fluid,
[data-theme="dark"] .container {
  background-color: var(--bg-color);
  color: var(--text-color);
}

[data-theme="dark"] h1, [data-theme="dark"] h2,
[data-theme="dark"] h3, [data-theme="dark"] h4 {
  color: var(--text-color) !important;
}

[data-theme="dark"] a { color: var(--link-color); }
[data-theme="dark"] code { background-color: var(--code-bg); color: #e0e0e0; }
[data-theme="dark"] pre { background-color: var(--code-bg); border-color: var(--card-border); }
[data-theme="dark"] .well { background-color: var(--well-bg); border-color: var(--card-border); }
[data-theme="dark"] .table-striped > tbody > tr:nth-of-type(odd) { background-color: var(--table-stripe); }
[data-theme="dark"] .table { color: var(--text-color); }
[data-theme="dark"] img { opacity: 0.9; }

/* Dark mode toggle button */
.dark-mode-toggle {
  background: none;
  border: none;
  font-size: 20px;
  cursor: pointer;
  padding: 8px 12px;
  margin-top: 8px;
  color: #9d9d9d;
  transition: color 0.2s;
}
.dark-mode-toggle:hover { color: #fff; }

/* Project cards */
.project-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 1.2em;
  margin: 1.5em 0;
}
.project-card {
  background: var(--card-bg);
  border: 1px solid var(--card-border);
  border-radius: 10px;
  padding: 1.4em;
  text-decoration: none !important;
  color: var(--text-color) !important;
  transition: transform 0.2s, box-shadow 0.2s;
  display: block;
  box-shadow: 0 2px 8px var(--card-shadow);
}
.project-card:hover {
  transform: translateY(-3px);
  box-shadow: 0 6px 20px var(--card-shadow);
  text-decoration: none !important;
}
.project-card .card-icon { font-size: 2em; margin-bottom: 0.4em; }
.project-card h3 { font-size: 1.05em; margin: 0 0 0.4em 0; color: var(--link-color) !important; }
.project-card p { font-size: 0.88em; color: var(--muted-text); margin: 0; line-height: 1.4; }

/* GitHub contribution chart */
.gh-contrib-link {
  display: block;
  text-decoration: none !important;
  margin: 1.2em 0 1.8em 0;
}
.gh-contrib-chart {
  display: block;
  width: 100%;
  max-width: 740px;
  height: auto;
  margin: 0 auto;
  padding: 1em;
  background: var(--card-bg);
  border: 1px solid var(--card-border);
  border-radius: 10px;
  box-shadow: 0 2px 8px var(--card-shadow);
  transition: box-shadow 0.2s;
}
.gh-contrib-link:hover .gh-contrib-chart {
  box-shadow: 0 6px 20px var(--card-shadow);
}
[data-theme="dark"] .gh-contrib-chart { opacity: 1; }

/* Figure captions (rendered from markdown image alt text) */
.float {
  margin-bottom: 2.5em;
}
.figcaption {
  font-size: 0.88em;
  font-style: italic;
  color: var(--muted-text);
  text-align: center;
  margin-top: 0.5em;
  line-height: 1.4;
}

/* Timestamp badges */
.data-timestamp {
  display: inline-block;
  background: var(--well-bg);
  border: 1px solid var(--card-border);
  border-radius: 4px;
  padding: 3px 10px;
  font-size: 0.82em;
  color: var(--muted-text);
  margin-bottom: 1em;
}

/* Collapsible table accordion styling */
details.table-accordion {
  margin: 1em 0;
}
details.table-accordion > summary {
  display: block;
  width: 100%;
  padding: 14px 20px;
  font-size: 1.1em;
  font-weight: 600;
  color: #fff;
  background: var(--accordion-bg);
  border: none;
  border-radius: 6px;
  cursor: pointer;
  list-style: none;
  text-align: center;
  transition: background 0.2s ease;
}
details.table-accordion > summary::-webkit-details-marker { display: none; }
details.table-accordion > summary::before {
  content: "\25B6\00a0\00a0";
  font-size: 0.85em;
}
details.table-accordion[open] > summary {
  border-radius: 6px 6px 0 0;
  background: var(--accordion-hover);
}
details.table-accordion[open] > summary::before {
  content: "\25BC\00a0\00a0";
}
details.table-accordion > summary:hover {
  background: var(--accordion-hover);
}
</style>
<script>
(function() {
  var saved = localStorage.getItem('theme') || 'light';
  if (saved === 'dark') document.documentElement.setAttribute('data-theme', 'dark');
})();
</script>
</style>
<!-- Meta tags for SEO and social sharing -->
<meta name="description" content="Cavan Donohoe - Data Scientist. Personal website showcasing data science projects, R tutorials, and professional experience.">
<meta name="keywords" content="data science, R programming, data analysis, R Markdown, Cavan Donohoe">
<meta name="author" content="Cavan Donohoe">
<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://cavandonohoe.github.io/">
<meta property="og:title" content="Cavan Donohoe - Data Scientist">
<meta property="og:description" content="Data Scientist passionate about making workflows easier through automation and reproducible analysis.">
<meta property="og:image" content="https://cavandonohoe.github.io/header/android-chrome-512x512.png">
<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://cavandonohoe.github.io/">
<meta property="twitter:title" content="Cavan Donohoe - Data Scientist">
<meta property="twitter:description" content="Data Scientist passionate about making workflows easier through automation and reproducible analysis.">
<meta property="twitter:image" content="https://cavandonohoe.github.io/header/android-chrome-512x512.png">

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Cavan Donohoe</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    About Me
  </a>
</li>
<li>
  <a href="services.html">
    <span class="fa fa-wrench"></span>
     
    Services
  </a>
</li>
<li>
  <a href="cv.html">
    <span class="fa fa-id-card"></span>
     
    CV
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-laptop"></span>
     
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">--- Movies &amp; TV ---</li>
    <li>
      <a href="imdb_top_250_tv_series.html">IMDb TV Series</a>
    </li>
    <li>
      <a href="imdb_rating_plot.html">IMDb Rating Plot by Season and Episode</a>
    </li>
    <li>
      <a href="top_250_imdb_with_rt.html">Top 250 IMDb Movies with Rotten Tomato Scores</a>
    </li>
    <li>
      <a href="best_picture_nominees.html">Best Picture Nominees</a>
    </li>
    <li>
      <a href="best_pic_vs_top_1000.html">Best Picture and Top 1000 Box Office</a>
    </li>
    <li>
      <a href="director_box_office_trajectory.html">Director Box Office Trajectory</a>
    </li>
    <li>
      <a href="my_imdb.html">My IMDb Ratings</a>
    </li>
    <li class="dropdown-header">--- Sports &amp; Personal ---</li>
    <li>
      <a href="avca_all_americans.html">AVCA Men's Volleyball All-Americans</a>
    </li>
    <li>
      <a href="firefighter_schedule.html">Jason, Owen, and Wyett's Firefighter Schedule</a>
    </li>
    <li>
      <a href="google_maps_saved_places.html">Google Maps: Want To Go + Favorites</a>
    </li>
    <li>
      <a href="my_travels.html">Get Bloggy With It</a>
    </li>
    <li>
      <a href="tohs_reunion.html">TOHS Class of 2012 Reunion</a>
    </li>
    <li class="dropdown-header">--- Visualizations ---</li>
    <li>
      <a href="confederate_statues.html">When Were Confederate Statues Erected?</a>
    </li>
    <li>
      <a href="sierpinski_triangle.html">Sierpinski Triangle</a>
    </li>
    <li>
      <a href="airplane_boarding.html">Airplane Boarding Simulation</a>
    </li>
    <li class="dropdown-header">--- Real Estate &amp; Finance ---</li>
    <li>
      <a href="us_rental_markets.html">US Rental Investment Markets</a>
    </li>
    <li>
      <a href="la_real_estate.html">LA Neighborhoods: Price per Sq Ft</a>
    </li>
    <li>
      <a href="la_housing_heatmap.html">LA Housing Prices: Animated Heat Map</a>
    </li>
    <li>
      <a href="https://cavandonohoe.shinyapps.io/rent-vs-buy/">Rent vs. Buy Calculator</a>
    </li>
    <li class="dropdown-header">--- Archive ---</li>
    <li>
      <a href="sp500.html">S&amp;P 500 Perspective</a>
    </li>
    <li>
      <a href="covid_cases_nostalgia.html">Covid Cases: Then &amp; Now</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-graduation-cap"></span>
     
    Learn R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="learn_r.html">Course Overview</a>
    </li>
    <li class="dropdown-header">--- Lessons ---</li>
    <li>
      <a href="intro_to_r.html">1. Introduction to R</a>
    </li>
    <li>
      <a href="basic_operations_r.html">2. Basic Operations</a>
    </li>
    <li>
      <a href="data_manipulation_r.html">3. Data Manipulation</a>
    </li>
    <li>
      <a href="data_visualization_r.html">4. Data Visualization</a>
    </li>
    <li>
      <a href="statistics_with_r.html">5. Statistics with R</a>
    </li>
    <li>
      <a href="rmarkdown_r.html">6. Reproducible Reports with R Markdown</a>
    </li>
    <li>
      <a href="capstone_r.html">7. Capstone Project</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lesson 5: Statistics with R</h1>
<h4 class="author">Cavan Donohoe</h4>

</div>


<p><link rel="stylesheet" href="/css/learn-r.css"></p>
<div class="course-progress">
<p>Lesson 5 of 7 · <a href="learn_r.html">Course overview</a></p>
</div>
<div id="statistics-with-r" class="section level1">
<h1>Statistics with R</h1>
<p>R was built by statisticians, so the basic statistics tools are right
there in the base language. This lesson covers the four things you’ll do
most often:</p>
<ol style="list-style-type: decimal">
<li>Descriptive statistics — summarising one variable.</li>
<li>Comparing two groups — the t-test.</li>
<li>Measuring association — correlation.</li>
<li>Modeling — linear regression, with diagnostics and predictions.</li>
</ol>
<p>We’ll keep using <code>mtcars</code> so you can compare the numbers
to the plots from Lesson 4.</p>
<div id="setup" class="section level2">
<h2>Setup</h2>
<pre class="r"><code>library(dplyr)
library(ggplot2)

cars &lt;- mtcars |&gt;
  tibble::rownames_to_column(&quot;model&quot;) |&gt;
  tibble::as_tibble()</code></pre>
</div>
<div id="descriptive-statistics" class="section level2">
<h2>Descriptive statistics</h2>
<p>The most common single-variable summaries:</p>
<pre class="r"><code>mean(cars$mpg)</code></pre>
<pre><code>#&gt; [1] 20.09</code></pre>
<pre class="r"><code>median(cars$mpg)</code></pre>
<pre><code>#&gt; [1] 19.2</code></pre>
<pre class="r"><code>sd(cars$mpg)              # standard deviation</code></pre>
<pre><code>#&gt; [1] 6.027</code></pre>
<pre class="r"><code>var(cars$mpg)             # variance</code></pre>
<pre><code>#&gt; [1] 36.32</code></pre>
<pre class="r"><code>min(cars$mpg)</code></pre>
<pre><code>#&gt; [1] 10.4</code></pre>
<pre class="r"><code>max(cars$mpg)</code></pre>
<pre><code>#&gt; [1] 33.9</code></pre>
<pre class="r"><code>range(cars$mpg)</code></pre>
<pre><code>#&gt; [1] 10.4 33.9</code></pre>
<pre class="r"><code>quantile(cars$mpg, probs = c(0.25, 0.5, 0.75))</code></pre>
<pre><code>#&gt;   25%   50%   75% 
#&gt; 15.43 19.20 22.80</code></pre>
<pre class="r"><code>IQR(cars$mpg)</code></pre>
<pre><code>#&gt; [1] 7.375</code></pre>
<p><code>summary()</code> prints a quick five-number summary plus the
mean — handy for a first look at any variable or data frame:</p>
<pre class="r"><code>summary(cars$mpg)</code></pre>
<pre><code>#&gt;    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#&gt;    10.4    15.4    19.2    20.1    22.8    33.9</code></pre>
<pre class="r"><code>summary(cars)</code></pre>
<pre><code>#&gt;        model         mpg            cyl            disp             hp       
#&gt;  Length   :32   Min.   :10.4   Min.   :4.00   Min.   : 71.1   Min.   : 52.0  
#&gt;  N.unique :32   1st Qu.:15.4   1st Qu.:4.00   1st Qu.:120.8   1st Qu.: 96.5  
#&gt;  N.blank  : 0   Median :19.2   Median :6.00   Median :196.3   Median :123.0  
#&gt;  Min.nchar: 7   Mean   :20.1   Mean   :6.19   Mean   :230.7   Mean   :146.7  
#&gt;  Max.nchar:19   3rd Qu.:22.8   3rd Qu.:8.00   3rd Qu.:326.0   3rd Qu.:180.0  
#&gt;                 Max.   :33.9   Max.   :8.00   Max.   :472.0   Max.   :335.0  
#&gt;       drat            wt            qsec            vs              am       
#&gt;  Min.   :2.76   Min.   :1.51   Min.   :14.5   Min.   :0.000   Min.   :0.000  
#&gt;  1st Qu.:3.08   1st Qu.:2.58   1st Qu.:16.9   1st Qu.:0.000   1st Qu.:0.000  
#&gt;  Median :3.69   Median :3.33   Median :17.7   Median :0.000   Median :0.000  
#&gt;  Mean   :3.60   Mean   :3.22   Mean   :17.8   Mean   :0.438   Mean   :0.406  
#&gt;  3rd Qu.:3.92   3rd Qu.:3.61   3rd Qu.:18.9   3rd Qu.:1.000   3rd Qu.:1.000  
#&gt;  Max.   :4.93   Max.   :5.42   Max.   :22.9   Max.   :1.000   Max.   :1.000  
#&gt;       gear           carb     
#&gt;  Min.   :3.00   Min.   :1.00  
#&gt;  1st Qu.:3.00   1st Qu.:2.00  
#&gt;  Median :4.00   Median :2.00  
#&gt;  Mean   :3.69   Mean   :2.81  
#&gt;  3rd Qu.:4.00   3rd Qu.:4.00  
#&gt;  Max.   :5.00   Max.   :8.00</code></pre>
<p>For grouped summaries, use <code>dplyr</code> from Lesson 3:</p>
<pre class="r"><code>cars |&gt;
  group_by(cyl) |&gt;
  summarise(
    n = n(),
    mean_mpg = mean(mpg),
    sd_mpg = sd(mpg),
    median_mpg = median(mpg),
    .groups = &quot;drop&quot;
  )</code></pre>
<pre><code>#&gt; # A tibble: 3 × 5
#&gt;     cyl     n mean_mpg sd_mpg median_mpg
#&gt;   &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1     4    11     26.7   4.51       26  
#&gt; 2     6     7     19.7   1.45       19.7
#&gt; 3     8    14     15.1   2.56       15.2</code></pre>
<div class="callout callout-tip">
<div class="callout-title">
💡 Always look before you test
</div>
<p>Before running a t-test or fitting a model, make a plot. A boxplot or
histogram will tell you in three seconds whether the assumptions you’re
about to make (normality, equal variance, no crazy outliers) are even
close to true.</p>
</div>
</div>
<div id="comparing-two-groups-the-t-test" class="section level2">
<h2>Comparing two groups: the t-test</h2>
<p>A t-test answers: “Are the means of two groups different by more than
I’d expect from random sampling?”</p>
<p>Question: do manual cars get better gas mileage than automatic cars
on average?</p>
<pre class="r"><code>ggplot(cars, aes(x = factor(am, labels = c(&quot;automatic&quot;, &quot;manual&quot;)), y = mpg)) +
  geom_boxplot(fill = &quot;lightsteelblue&quot;) +
  labs(x = &quot;Transmission&quot;, y = &quot;MPG&quot;, title = &quot;MPG by transmission type&quot;) +
  theme_minimal()</code></pre>
<p><img src="statistics_with_r_files/figure-html/unnamed-chunk-5-1.png" alt="" width="650" /></p>
<p>The boxplot suggests yes. Let’s quantify it:</p>
<pre class="r"><code>t_result &lt;- t.test(mpg ~ am, data = cars)
t_result</code></pre>
<pre><code>#&gt; 
#&gt;  Welch Two Sample t-test
#&gt; 
#&gt; data:  mpg by am
#&gt; t = -3.8, df = 18, p-value = 0.001
#&gt; alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -11.28  -3.21
#&gt; sample estimates:
#&gt; mean in group 0 mean in group 1 
#&gt;           17.15           24.39</code></pre>
<p>How to read the output:</p>
<ul>
<li><strong><code>t = -3.77</code></strong> — the test statistic. Bigger
absolute value = stronger evidence the means differ.</li>
<li><strong><code>df</code></strong> — degrees of freedom (Welch’s
t-test uses fractional df, that’s fine).</li>
<li><strong><code>p-value = 0.001374</code></strong> — probability of
seeing a difference this large (or larger) if the true means were
actually equal. By the conventional cutoff of 0.05, this is
“significant.”</li>
<li><strong><code>95 percent confidence interval: -11.28, -3.21</code></strong>
— we’re 95% confident the true difference (automatic minus manual) is
between about -11 and -3 MPG.</li>
<li><strong><code>mean in group 0 = 17.15, mean in group 1 = 24.39</code></strong>
— the actual group means.</li>
</ul>
<p>So manual cars in this dataset get around <strong>7 MPG more</strong>
than automatic cars on average, and the difference is statistically
significant.</p>
<p>You can pull individual pieces out programmatically:</p>
<pre class="r"><code>t_result$p.value</code></pre>
<pre><code>#&gt; [1] 0.001374</code></pre>
<pre class="r"><code>t_result$conf.int</code></pre>
<pre><code>#&gt; [1] -11.28  -3.21
#&gt; attr(,&quot;conf.level&quot;)
#&gt; [1] 0.95</code></pre>
<pre class="r"><code>t_result$estimate</code></pre>
<pre><code>#&gt; mean in group 0 mean in group 1 
#&gt;           17.15           24.39</code></pre>
<div class="callout callout-warning">
<div class="callout-title">
⚠️ “Significant” doesn’t mean “important”
</div>
<p>A tiny effect with a huge sample will be “statistically significant.”
A huge effect with a small sample may not be. Always look at the
confidence interval and the effect size, not just the p-value.</p>
<p>Also: this comparison ignores that manuals tend to be in different
cars than automatics (lighter, fewer cylinders, etc.). The honest answer
to “does transmission cause better MPG” requires a model that controls
for those things — that’s what regression is for.</p>
</div>
</div>
<div id="measuring-association-correlation" class="section level2">
<h2>Measuring association: correlation</h2>
<p>Correlation measures how strongly two numeric variables move
together, on a scale of -1 to 1.</p>
<pre class="r"><code>cor(cars$wt, cars$mpg)</code></pre>
<pre><code>#&gt; [1] -0.8677</code></pre>
<p>A correlation of about -0.87: strong negative association. As weight
goes up, MPG goes down.</p>
<p><code>cor.test()</code> adds a hypothesis test (is the correlation
different from zero?) and a confidence interval:</p>
<pre class="r"><code>cor.test(cars$wt, cars$mpg)</code></pre>
<pre><code>#&gt; 
#&gt;  Pearson&#39;s product-moment correlation
#&gt; 
#&gt; data:  cars$wt and cars$mpg
#&gt; t = -9.6, df = 30, p-value = 0.0000000001
#&gt; alternative hypothesis: true correlation is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.9338 -0.7441
#&gt; sample estimates:
#&gt;     cor 
#&gt; -0.8677</code></pre>
<p>For a whole correlation matrix:</p>
<pre class="r"><code>cars |&gt;
  select(mpg, hp, wt, drat, qsec) |&gt;
  cor() |&gt;
  round(2)</code></pre>
<pre><code>#&gt;        mpg    hp    wt  drat  qsec
#&gt; mpg   1.00 -0.78 -0.87  0.68  0.42
#&gt; hp   -0.78  1.00  0.66 -0.45 -0.71
#&gt; wt   -0.87  0.66  1.00 -0.71 -0.17
#&gt; drat  0.68 -0.45 -0.71  1.00  0.09
#&gt; qsec  0.42 -0.71 -0.17  0.09  1.00</code></pre>
</div>
<div id="linear-regression" class="section level2">
<h2>Linear regression</h2>
<p>Regression is the workhorse of applied statistics. The basic
question: “How does the response variable change as the predictors
change?”</p>
<div id="a-simple-regression" class="section level3">
<h3>A simple regression</h3>
<p>Predict MPG from weight:</p>
<pre class="r"><code>fit1 &lt;- lm(mpg ~ wt, data = cars)
fit1</code></pre>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = mpg ~ wt, data = cars)
#&gt; 
#&gt; Coefficients:
#&gt; (Intercept)           wt  
#&gt;       37.29        -5.34</code></pre>
<p>The formula <code>mpg ~ wt</code> reads as “model <code>mpg</code> as
a function of <code>wt</code>.” <code>lm()</code> returns a fitted model
object — print it for a quick look, <code>summary()</code> for the full
output:</p>
<pre class="r"><code>summary(fit1)</code></pre>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = mpg ~ wt, data = cars)
#&gt; 
#&gt; Residuals:
#&gt;    Min     1Q Median     3Q    Max 
#&gt; -4.543 -2.365 -0.125  1.410  6.873 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value             Pr(&gt;|t|)    
#&gt; (Intercept)   37.285      1.878   19.86 &lt; 0.0000000000000002 ***
#&gt; wt            -5.344      0.559   -9.56        0.00000000013 ***
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Residual standard error: 3.05 on 30 degrees of freedom
#&gt; Multiple R-squared:  0.753,  Adjusted R-squared:  0.745 
#&gt; F-statistic: 91.4 on 1 and 30 DF,  p-value: 0.000000000129</code></pre>
<p>What’s important here:</p>
<ul>
<li><strong>Coefficients:</strong> <code>wt = -5.34</code> means each
additional 1000 lbs of weight is associated with a <strong>5.34-MPG
decrease</strong>, on average.</li>
<li><strong><code>Pr(&gt;|t|)</code> for <code>wt</code>:</strong> the
p-value for “is this coefficient different from 0?” Tiny — yes.</li>
<li><strong>R-squared = 0.75:</strong> 75% of the variation in MPG is
explained by weight alone.</li>
<li><strong>Residual standard error:</strong> typical prediction error
in MPG units.</li>
</ul>
</div>
<div id="a-multiple-regression" class="section level3">
<h3>A multiple regression</h3>
<p>Add more predictors with <code>+</code>:</p>
<pre class="r"><code>fit2 &lt;- lm(mpg ~ wt + hp + factor(cyl), data = cars)
summary(fit2)</code></pre>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = mpg ~ wt + hp + factor(cyl), data = cars)
#&gt; 
#&gt; Residuals:
#&gt;    Min     1Q Median     3Q    Max 
#&gt; -4.261 -1.032 -0.321  0.928  5.395 
#&gt; 
#&gt; Coefficients:
#&gt;              Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept)   35.8460     2.0410   17.56 0.00000000000000027 ***
#&gt; wt            -3.1814     0.7196   -4.42             0.00014 ***
#&gt; hp            -0.0231     0.0120   -1.93             0.06361 .  
#&gt; factor(cyl)6  -3.3590     1.4017   -2.40             0.02375 *  
#&gt; factor(cyl)8  -3.1859     2.1705   -1.47             0.15370    
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Residual standard error: 2.44 on 27 degrees of freedom
#&gt; Multiple R-squared:  0.857,  Adjusted R-squared:  0.836 
#&gt; F-statistic: 40.5 on 4 and 27 DF,  p-value: 0.0000000000487</code></pre>
<p>Now we’re estimating the effect of weight <strong>after controlling
for</strong> horsepower and cylinder count.</p>
<p><code>factor(cyl)</code> tells R to treat <code>cyl</code> as a
categorical variable rather than a number. The output gives you the
difference between each level and a reference level (here,
4-cylinder).</p>
</div>
<div id="comparing-models" class="section level3">
<h3>Comparing models</h3>
<p><code>anova()</code> tests whether the bigger model is significantly
better than the smaller one:</p>
<pre class="r"><code>anova(fit1, fit2)</code></pre>
<pre><code>#&gt; Analysis of Variance Table
#&gt; 
#&gt; Model 1: mpg ~ wt
#&gt; Model 2: mpg ~ wt + hp + factor(cyl)
#&gt;   Res.Df RSS Df Sum of Sq    F Pr(&gt;F)   
#&gt; 1     30 278                            
#&gt; 2     27 161  3       118 6.58 0.0018 **
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>A small p-value means the extra predictors are pulling weight (so to
speak).</p>
<p><code>AIC()</code> and <code>BIC()</code> are alternative
model-comparison metrics — lower is better:</p>
<pre class="r"><code>AIC(fit1, fit2)</code></pre>
<pre><code>#&gt;      df   AIC
#&gt; fit1  3 166.0
#&gt; fit2  6 154.5</code></pre>
</div>
<div id="diagnostics" class="section level3">
<h3>Diagnostics</h3>
<p>Before trusting a regression, look at the diagnostic plots. R’s
built-in <code>plot()</code> on a model gives you four:</p>
<pre class="r"><code>par(mfrow = c(2, 2))
plot(fit1)</code></pre>
<p><img src="statistics_with_r_files/figure-html/unnamed-chunk-16-1.png" alt="" width="700" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>What you’re looking for:</p>
<ul>
<li><strong>Residuals vs. Fitted</strong> — should look like a flat blob
with no pattern. A curve suggests you’re missing nonlinearity.</li>
<li><strong>Q-Q Residuals</strong> — should hug the diagonal line. Big
departures = non-normal residuals.</li>
<li><strong>Scale-Location</strong> — should be roughly flat. A trend
means the variance changes with the fitted value
(heteroscedasticity).</li>
<li><strong>Residuals vs. Leverage</strong> — points with high Cook’s
distance (top-right or bottom-right corners, past the dashed lines) are
unusually influential. Investigate those rows.</li>
</ul>
</div>
<div id="predictions" class="section level3">
<h3>Predictions</h3>
<p>Once you have a model, you can predict new values:</p>
<pre class="r"><code>new_cars &lt;- tibble::tibble(wt = c(2.0, 3.5, 5.0))
predict(fit1, newdata = new_cars)</code></pre>
<pre><code>#&gt;     1     2     3 
#&gt; 26.60 18.58 10.56</code></pre>
<p>Add a confidence interval for the <em>mean</em> response:</p>
<pre class="r"><code>predict(fit1, newdata = new_cars, interval = &quot;confidence&quot;)</code></pre>
<pre><code>#&gt;     fit    lwr   upr
#&gt; 1 26.60 24.824 28.37
#&gt; 2 18.58 17.433 19.73
#&gt; 3 10.56  8.249 12.88</code></pre>
<p>Or a prediction interval for a <em>single new observation</em>
(wider, because individual cars vary):</p>
<pre class="r"><code>predict(fit1, newdata = new_cars, interval = &quot;prediction&quot;)</code></pre>
<pre><code>#&gt;     fit    lwr   upr
#&gt; 1 26.60 20.128 33.06
#&gt; 2 18.58 12.254 24.90
#&gt; 3 10.56  3.926 17.20</code></pre>
</div>
<div id="visualizing-the-fit" class="section level3">
<h3>Visualizing the fit</h3>
<p>A simple regression line is one geom away in ggplot:</p>
<pre class="r"><code>ggplot(cars, aes(x = wt, y = mpg)) +
  geom_point(size = 2.5, alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;, se = TRUE, color = &quot;steelblue&quot;) +
  labs(
    title = &quot;MPG vs. Weight, with linear fit and 95% CI&quot;,
    x = &quot;Weight (1000 lbs)&quot;, y = &quot;MPG&quot;
  ) +
  theme_minimal()</code></pre>
<p><img src="statistics_with_r_files/figure-html/unnamed-chunk-20-1.png" alt="" width="650" /></p>
<p><code>geom_smooth(method = "lm")</code> is fitting the same model as
<code>lm(mpg ~ wt)</code> under the hood and shading the confidence
band.</p>
</div>
</div>
<div id="a-few-other-tests-worth-knowing" class="section level2">
<h2>A few other tests worth knowing</h2>
<ul>
<li><code>wilcox.test()</code> — non-parametric alternative to the
t-test (for non-normal data).</li>
<li><code>chisq.test()</code> — chi-square test for independence between
two categorical variables.</li>
<li><code>prop.test()</code> — comparing proportions across groups.</li>
<li><code>aov()</code> — ANOVA, for comparing means across more than two
groups.</li>
<li><code>glm(..., family = binomial)</code> — logistic regression, for
binary outcomes.</li>
</ul>
<p>The pattern is the same across all of them: a formula, a data
argument, a summary or print of the result.</p>
</div>
<div id="putting-it-together" class="section level2">
<h2>Putting it together</h2>
<p>A complete mini-analysis: is MPG associated with weight, controlling
for horsepower? Report the model, check assumptions, and predict MPG for
a hypothetical new car.</p>
<pre class="r"><code>fit &lt;- lm(mpg ~ wt + hp, data = cars)
summary(fit)</code></pre>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = mpg ~ wt + hp, data = cars)
#&gt; 
#&gt; Residuals:
#&gt;    Min     1Q Median     3Q    Max 
#&gt; -3.941 -1.600 -0.182  1.050  5.854 
#&gt; 
#&gt; Coefficients:
#&gt;             Estimate Std. Error t value             Pr(&gt;|t|)    
#&gt; (Intercept) 37.22727    1.59879   23.28 &lt; 0.0000000000000002 ***
#&gt; wt          -3.87783    0.63273   -6.13            0.0000011 ***
#&gt; hp          -0.03177    0.00903   -3.52               0.0015 ** 
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Residual standard error: 2.59 on 29 degrees of freedom
#&gt; Multiple R-squared:  0.827,  Adjusted R-squared:  0.815 
#&gt; F-statistic: 69.2 on 2 and 29 DF,  p-value: 0.00000000000911</code></pre>
<p>Coefficient interpretations: holding horsepower constant, each
additional 1000 lbs of weight is associated with a -3.88-MPG decrease.
Holding weight constant, each additional horsepower is associated with a
-0.0318-MPG decrease.</p>
<p>Quick diagnostic look:</p>
<pre class="r"><code>par(mfrow = c(1, 2))
plot(fit, which = c(1, 2))</code></pre>
<p><img src="statistics_with_r_files/figure-html/unnamed-chunk-22-1.png" alt="" width="700" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>Predict MPG for a 3500-lb car with 130 hp:</p>
<pre class="r"><code>predict(fit, newdata = tibble::tibble(wt = 3.5, hp = 130), interval = &quot;prediction&quot;)</code></pre>
<pre><code>#&gt;     fit  lwr   upr
#&gt; 1 19.52 14.1 24.95</code></pre>
<p>That’s a complete (if minimal) regression analysis: fit, interpret,
diagnose, predict.</p>
<div class="exercise">
<div class="exercise-title">
✏️ Exercise 5.1 — Descriptive stats
</div>
<p>Compute the mean, median, standard deviation, and IQR of
<code>cars$hp</code>. Are the mean and median similar? What does that
tell you about the distribution?</p>
<details>
<summary>
Show solution
</summary>
<pre class="r"><code>mean(cars$hp)</code></pre>
<pre><code>#&gt; [1] 146.7</code></pre>
<pre class="r"><code>median(cars$hp)</code></pre>
<pre><code>#&gt; [1] 123</code></pre>
<pre class="r"><code>sd(cars$hp)</code></pre>
<pre><code>#&gt; [1] 68.56</code></pre>
<pre class="r"><code>IQR(cars$hp)</code></pre>
<pre><code>#&gt; [1] 83.5</code></pre>
<p>The mean is noticeably higher than the median, which means the
distribution is right-skewed — there are a few high-horsepower outliers
pulling the mean up. A boxplot or histogram would confirm.</p>
<pre class="r"><code>ggplot(cars, aes(x = hp)) +
  geom_histogram(bins = 12, fill = &quot;steelblue&quot;, color = &quot;white&quot;) +
  theme_minimal()</code></pre>
<p><img src="statistics_with_r_files/figure-html/unnamed-chunk-25-1.png" alt="" width="650" /></p>
</details>
</div>
<div class="exercise">
<div class="exercise-title">
✏️ Exercise 5.2 — A t-test
</div>
<p>Test whether 4-cylinder cars have a different mean MPG than
8-cylinder cars. Report the p-value, the 95% CI, and a one-sentence
interpretation.</p>
<details>
<summary>
Show solution
</summary>
<pre class="r"><code>sub &lt;- cars |&gt; filter(cyl %in% c(4, 8))
t.test(mpg ~ cyl, data = sub)</code></pre>
<pre><code>#&gt; 
#&gt;  Welch Two Sample t-test
#&gt; 
#&gt; data:  mpg by cyl
#&gt; t = 7.6, df = 15, p-value = 0.000002
#&gt; alternative hypothesis: true difference in means between group 4 and group 8 is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;   8.319 14.809
#&gt; sample estimates:
#&gt; mean in group 4 mean in group 8 
#&gt;           26.66           15.10</code></pre>
<p>The mean MPG of 4-cylinder cars is roughly 11 MPG higher than
8-cylinder cars (95% CI ~9 to 13), and the p-value is tiny — the
difference is far more than chance.</p>
</details>
</div>
<div class="exercise">
<div class="exercise-title">
✏️ Exercise 5.3 — A regression
</div>
<p>Fit a model that predicts MPG from weight, horsepower, and cylinder
count (treat <code>cyl</code> as a factor). Which coefficients are
statistically significant? What’s the R-squared?</p>
<details>
<summary>
Show solution
</summary>
<pre class="r"><code>fit &lt;- lm(mpg ~ wt + hp + factor(cyl), data = cars)
summary(fit)</code></pre>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = mpg ~ wt + hp + factor(cyl), data = cars)
#&gt; 
#&gt; Residuals:
#&gt;    Min     1Q Median     3Q    Max 
#&gt; -4.261 -1.032 -0.321  0.928  5.395 
#&gt; 
#&gt; Coefficients:
#&gt;              Estimate Std. Error t value            Pr(&gt;|t|)    
#&gt; (Intercept)   35.8460     2.0410   17.56 0.00000000000000027 ***
#&gt; wt            -3.1814     0.7196   -4.42             0.00014 ***
#&gt; hp            -0.0231     0.0120   -1.93             0.06361 .  
#&gt; factor(cyl)6  -3.3590     1.4017   -2.40             0.02375 *  
#&gt; factor(cyl)8  -3.1859     2.1705   -1.47             0.15370    
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Residual standard error: 2.44 on 27 degrees of freedom
#&gt; Multiple R-squared:  0.857,  Adjusted R-squared:  0.836 
#&gt; F-statistic: 40.5 on 4 and 27 DF,  p-value: 0.0000000000487</code></pre>
<p><code>wt</code> has a clearly significant negative coefficient.
<code>hp</code> and the cylinder-count contrasts get smaller and may no
longer be significant once weight is in the model — they’re correlated
with weight (heavier cars tend to have more cylinders and more
horsepower), so a lot of the “effect” of cylinders is really just
weight. Adjusted R-squared should be around 0.83.</p>
</details>
</div>
</div>
<div id="whats-next" class="section level2">
<h2>What’s next</h2>
<p>You can now load data, manipulate it, plot it, and run real
statistical analyses on it. The last two lessons stop adding new tools
and start showing how to <strong>package up an analysis</strong> so
someone else (or future-you) can run it again. Lesson 6 is R Markdown —
the document format this whole course is written in.</p>
<div class="lesson-nav">
<p><a class="nav-prev" href="data_visualization_r.html"> <span
class="lesson-nav-label">← Previous</span> <span
class="lesson-nav-title">Lesson 4: Data Visualization</span> </a>
<a class="nav-next" href="rmarkdown_r.html"> <span
class="lesson-nav-label">Next →</span> <span
class="lesson-nav-title">Lesson 6: Reproducible Reports</span> </a></p>
</div>
</div>
</div>

<link rel="stylesheet" href="/css/footer.css">
<footer id="footer_stuff" class="band full" role="contentinfo">
  <div class="bandContent">
    <p id="full_send">Feel free to contact me:</p>
    <nav id="logos" aria-label="Social media and contact links">
      <a href="mailto:cavandonohoe@gmail.com" aria-label="Email Cavan Donohoe"><i class="fa fa-envelope" style="font-size:22px"></i></a>
      <a href="https://www.instagram.com/cavandonohoe" aria-label="Instagram profile" rel="noopener noreferrer"><i class="fa fa-instagram" style="font-size:22px"></i></a>
      <a href="https://www.facebook.com/cavandonohoe" aria-label="Facebook profile" rel="noopener noreferrer"><i class="fa fa-facebook" style="font-size:22px"></i></a>
      <a href="https://github.com/cavandonohoe" aria-label="GitHub profile" rel="noopener noreferrer"><i class="fa fa-github" style="font-size:22px"></i></a>
      <a href="https://www.linkedin.com/in/cavan-donohoe/" aria-label="LinkedIn profile" rel="noopener noreferrer"><i class="fa fa-linkedin" style="font-size:22px"></i></a>
      <a href="tel:+8054043321" aria-label="Phone number"><i class="fa fa-phone" style="font-size:22px"></i></a>
    </nav>
  </div>
</footer>
<script>
(function() {
  function addLabel(el, label) {
    if (!el) return;
    if (el.hasAttribute('aria-label') && el.getAttribute('aria-label').trim()) return;
    if (el.hasAttribute('title') && el.getAttribute('title').trim()) return;
    el.setAttribute('aria-label', label);
  }

  function labelNavbarToggle() {
    var toggles = document.querySelectorAll('button.navbar-toggle');
    for (var i = 0; i < toggles.length; i++) {
      addLabel(toggles[i], 'Toggle navigation');
    }
  }

  function labelPlotlyModebar() {
    var anchors = document.querySelectorAll('.modebar-container a, [id^="modebar-"] a');
    for (var i = 0; i < anchors.length; i++) {
      var a = anchors[i];
      if ((a.hasAttribute('aria-label') && a.getAttribute('aria-label').trim()) ||
          (a.hasAttribute('title') && a.getAttribute('title').trim())) {
        // already labeled — but H91 still wants id/name on empty anchors,
        // so ensure that too.
      } else {
        var dataTitle = a.getAttribute('data-title') || '';
        var label = dataTitle.trim() || 'Plot toolbar action';
        a.setAttribute('aria-label', label);
      }
      // H91 considers an empty anchor accessible if it has id or name.
      // Give every modebar anchor a stable, unique id derived from the
      // parent modebar id + position so HTML_CodeSniffer stops flagging.
      if (!a.id) {
        var parent = a.closest('[id^="modebar-"]');
        var base = parent ? parent.id : 'modebar';
        var idx = Array.prototype.indexOf.call(parent ? parent.querySelectorAll('a') : [a], a);
        a.id = base + '-btn-' + (idx >= 0 ? idx : i);
      }
      if (!a.getAttribute('name')) a.setAttribute('name', a.id);
    }
  }

  function dedupePlotlySymbolIds() {
    // Plotly inlines an SVG icon set per chart that defines <g id="symbol">,
    // so pages with two charts trip F77 (duplicate id). Drop the id on every
    // occurrence after the first; nothing on the page references #symbol.
    // Restrict to the known offender so we don't accidentally rename
    // legitimate duplicates elsewhere.
    var symbols = document.querySelectorAll('[id="symbol"]');
    for (var i = 1; i < symbols.length; i++) {
      symbols[i].removeAttribute('id');
    }
  }

  function labelDataTablesControls() {
    var inputs = document.querySelectorAll(
      '.dataTables_wrapper input[type="search"], .dataTables_wrapper input[type="text"], ' +
      'table.dataTable thead input[type="search"], table.dataTable thead input[type="text"]'
    );
    for (var i = 0; i < inputs.length; i++) {
      var input = inputs[i];
      if ((input.hasAttribute('aria-label') && input.getAttribute('aria-label').trim()) ||
          (input.hasAttribute('title') && input.getAttribute('title').trim())) continue;
      var placeholder = input.getAttribute('placeholder') || '';
      var label = placeholder.trim() || 'Search';
      var th = input.closest('th, td');
      var col = th ? (th.getAttribute('aria-label') || th.textContent || '').trim() : '';
      if (col) label = col + ' search';
      input.setAttribute('aria-label', label);
    }

    var selects = document.querySelectorAll(
      '.dataTables_wrapper select, table.dataTable thead select'
    );
    for (var j = 0; j < selects.length; j++) {
      var sel = selects[j];
      if ((sel.hasAttribute('aria-label') && sel.getAttribute('aria-label').trim()) ||
          (sel.hasAttribute('title') && sel.getAttribute('title').trim())) continue;
      var th2 = sel.closest('th, td');
      var col2 = th2 ? (th2.getAttribute('aria-label') || th2.textContent || '').trim() : '';
      sel.setAttribute('aria-label', col2 ? col2 + ' filter' : 'Column filter');
    }
  }

  function applyA11yShims() {
    labelNavbarToggle();
    labelPlotlyModebar();
    labelDataTablesControls();
    dedupePlotlySymbolIds();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', applyA11yShims);
  } else {
    applyA11yShims();
  }

  // Plotly and DataTables can re-render after initial load; reapply on a short
  // delay and observe further DOM changes so dynamically-inserted controls
  // also get labelled before the pa11y wait window expires.
  setTimeout(applyA11yShims, 250);
  setTimeout(applyA11yShims, 1000);

  if (typeof MutationObserver !== 'undefined') {
    var observer = new MutationObserver(function() { applyA11yShims(); });
    observer.observe(document.body, { childList: true, subtree: true });
  }
})();
</script>
<script>
(function() {
  var btn = document.createElement('button');
  btn.className = 'dark-mode-toggle';
  btn.setAttribute('aria-label', 'Toggle dark mode');
  btn.innerHTML = localStorage.getItem('theme') === 'dark' ? '☀️' : '🌙';
  btn.onclick = function() {
    var current = document.documentElement.getAttribute('data-theme');
    var next = current === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    localStorage.setItem('theme', next);
    btn.innerHTML = next === 'dark' ? '☀️' : '🌙';
  };
  var navbar = document.querySelector('.navbar-right') || document.querySelector('.navbar-nav');
  if (navbar) {
    var li = document.createElement('li');
    li.appendChild(btn);
    navbar.appendChild(li);
  }
})();
</script>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
