---
title: "R Time Is Limited, Let's Make the Most of It"
author: "Cavan Donohoe"
output:
  html_document:
    self_contained: false
    toc: true
    toc_float: true
    includes:
      in_header: ../header/header.html
      after_body: ../include_footer.html
---

Welcome to the "R Time Is Limited, Let's Make the Most of It" class! In this course, you will learn the basics of R programming and data analysis. R is a powerful and versatile programming language for statistical analysis, data visualization, and more.

## Course Objectives

In this course, you will:

1. Learn the fundamentals of R programming.
2. Explore data manipulation and analysis.
3. Create informative data visualizations.
4. Gain practical experience through hands-on exercises.

## Getting Started

Before we dive into the world of R, make sure you have R and RStudio installed on your computer. You can download them from the following links:

- [R](https://cran.r-project.org/mirrors.html)
- [RStudio](https://www.rstudio.com/products/rstudio/download/)

## What You Will Need

- A computer with R and RStudio installed.
- Curiosity and enthusiasm to learn!

## Course Outline

1. **Introduction to R**
   - What is R?
   - Installing R and RStudio.
   - RStudio interface overview.

2. **Basic Operations in R**
   - Variables and data types.
   - Arithmetic operations.
   - Working with vectors and matrices.

3. **Data Manipulation**
   - Importing and exporting data.
   - Data frames and data exploration.

4. **Data Visualization**
   - Creating basic plots.
   - Customizing plots.
   - Advanced visualization with ggplot2.

5. **Statistics with R**
   - Descriptive statistics.
   - Hypothesis testing.
   - Regression analysis.

## Contact Information

If you have any questions or need further assistance during the course, please don't hesitate to contact me:

- **Email:** cavandonohoe@gmail.com

Feel free to reach out for clarification, additional resources, or any other inquiries.

Let's embark on this exciting journey of learning R together!



Free Lessons:

- [R Time Is Limited, Let's Make the Most of It](https://cavandonohoe.github.io/learn_r.html)
- [Introduction to R](https://cavandonohoe.github.io/intro_to_r.html)
- [Basic Operations in R](https://cavandonohoe.github.io/basic_operations_r.html)
- [Data Manipulation](https://cavandonohoe.github.io/data_manipulation_r.html)
- [Data Visualization](https://cavandonohoe.github.io/data_visualization_r.html)
- [Statistics in R](https://cavandonohoe.github.io/statistics_with_r.html)
