name: Build & Deploy R Markdown site
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: rmarkdown, here, rprojroot, knitr, readr
      - name: Render site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Add .nojekyll
        run: touch _site/.nojekyll
      - name: Deploy to gh-pages (root)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
          clean: true
