name: PR Preview (R Markdown → GitHub Pages)

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: rmarkdown, knitr, rprojroot, here, readr

      - name: Render site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Show what got built
        run: |
          echo "--- _site tree ---"
          find _site -maxdepth 3 -type f | sed 's|^|_site/|'
          echo "--- end tree ---"

      - name: Ensure preview has an entry page
        run: |
          if [ -f _site/reports/index.html ]; then
            echo '<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=reports/index.html">' > _site/index.html
          fi
          # hard fail if no HTML was produced
          test "$(find _site -name '*.html' | wc -l)" -gt 0

      - name: Deploy PR preview to gh-pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
