name: PR Preview (R Markdown → GitHub Pages)

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

# avoid overlapping publishes for the same PR
concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      # Install the packages your site needs to render
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: rmarkdown, knitr, rprojroot, here, readr, dplyr, ggplot2

      - name: Render site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Show what got built
        run: |
          echo '--- _site tree (first 200 files) ---'
          find _site -type f | head -n 200
          echo '--- end tree ---'

      - name: Ensure preview has an entry page
        run: |
          # if your entry lives under reports/, create a redirect at _site/index.html
          if [ -f _site/reports/index.html ]; then
            echo '<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=reports/index.html">' > _site/index.html
          fi

          # ensure Pages treats this as a static site
          touch _site/.nojekyll

          # hard fail if the build produced no HTML
          test "$(find _site -name '*.html' | wc -l)" -gt 0

      # (Optional) sanity check route; visit /hello.html if you need to debug
      - name: Drop a debug file
        run: echo 'ok' > _site/hello.html

      - name: Deploy PR preview to gh-pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
