name: PR Preview (R Markdown → GitHub Pages)

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

# prevent overlapping publishes for the same PR
concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      # Install the packages your pages commonly use
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: rmarkdown, knitr, rprojroot, here, readr, dplyr, ggplot2

      - name: Render site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'

      - name: Show what got built
        run: |
          echo '--- _site tree (first 200 files) ---'
          find _site -type f | head -n 200
          echo '--- end tree ---'

      - name: Prepare preview folder
        run: |
          set -e
          # Ensure entry exists (root index.html since index.Rmd is at repo root)
          test -f _site/index.html
          # Make sure Pages treats this as static content
          touch _site/.nojekyll
          # Optional debug file (uncomment if you want to sanity-check via /hello.html)
          # echo 'ok' > _site/hello.html
          # Fail fast if no HTML at all
          test "$(find _site -name '*.html' | wc -l)" -gt 0

      - name: Deploy PR preview to gh-pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
